name: NodeJS Build

on:
  release:
    types: [published]

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run build          
      
      - name: Get the release ID
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const release_id = context.payload.release.id;
            core.setOutput('release_id', release_id);
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/*.AppImage
          asset_name: PsiphonVPN_Linux.AppImage
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
